### ISSUE TITLE
New theme for the gallery: Supervillain

### ISSUE THREAD

**Issue by trumbitta** [divshot/themestrap#13]
I'm working on a port / modification of my favorite Bootswatch theme from version 2, which seems to be gone now: [Superhero](http://bootswatch.com/2/superhero/).

Mine is [Supervillain](http://trumbitta.github.io/bootstrap-theme-supervillain/) :sunglasses: 
Still a work in progress, but it's getting there...

Do you guys think it's worth including in the gallery?

I'd like feedback from @mbleigh @eins78 and @fastdivision

**Comment by mbleigh** [comment]
Looks nice! If you make a PR to the gh-pages branch that adds in your theme I'll happily merge it.

**Comment by trumbitta** [comment]
Hey @mbleigh thanks!
Actually you gave me push privileges a couple weeks ago, but I kinda always thought you intended to gave them to @eins78 for all his contributions :)

I'm trying not to misuse them, hence the request for feedback!

**Comment by mbleigh** [comment]
Hey, open source needs all the help it can get (though I think I did misprivelege). @eins78 you've got push now, and @trumbitta feel free to push your theme to the gallery!

**Comment by trumbitta** [comment]
Congratz @eins78 , you deserved it!

Thanks @mbleigh , doing it right now, and then :sleeping:

**Comment by fastdivision** [comment]
It's great to see more themes! Here's a few suggestions, although I know it's a WIP and you may already have some of these changes in mind:
- Improve the contrast of the various paragraph colors.
- I like the dark #37414C color in the table and nav. Would be nice to see used as the border color in .page-header, horizontal rules, legend, etc.
- A brighter orange than #e36b23 might add more pop: #FF7F32.
- An inverted dark version of input boxes and textareas might be cool.

Thanks for contributing @trumbitta!

**Comment by trumbitta** [comment]
thanks @fastdivision I'll work in your suggestions asap.

I borrowed the color codes from Superhero, but I'm certainly open to improvements and will try them for sure.

**Comment by trumbitta** [comment]
@fastdivision here's some updates: http://trumbitta.github.io/bootstrap-theme-supervillain/examples/kitchen-sink.html

Your feedback inspired me a lot, I'm quite happy with the results now :+1: 
There must be some hidden corners waiting to be styled, but that is work for another day...

**Comment by fastdivision** [comment]
@trumbitta It looks fantastic! I love the orange glow when focused on form elements. Here's some additional feedback (very minor changes) when you get around to the hidden corners:
- Improve the contrast of the orange text against the pagination item hover highlight (maybe brighter orange?).
- Remove the text shadow from the alert close button.
- Use the border color as the box-shadow when focusing on warning/error/success form group controls like input boxes for a brighter glow.

That's all I have to say. Great theme!

**Comment by eins78** [comment]
I was on holiday while this thread happened and haven't come around till now.
So, thanks @mbleigh :blush: 

Regarding the theme: I like it and have only one small thing to add to what @fastdivision already mentioned:
I find the 'danger'-red a little bit shy. The color looks nice in context, but I'm not shure if it comes off as 'dangerous', especially because the 'primary' color is such a (nice, but) bright orange.
